typography_spectrum: 0.1728
color:
  brandColors:
    - '#151515'
    - '#5f5f5f'
    - '#ffffff'
    - '#848484'
    - '#adadad'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1043
analytics:
  google: null
  facebook: null
  twitter: null
name: Joshua Harmon
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Josh & Food
    id: c945a623-d2df-46c6-93a5-3d9d0c211ffc
    type: content
favicon: null
purpose: []
