name: Joshua Harmon
favicon: null
layout_spectrum: 0.4084680499508977
typography_spectrum: 0.58309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#5f5f5f'
    - '#ffffff'
    - '#848484'
    - '#adadad'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
